### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by erik78se** [omnivector-solutions/layer-slurm-controller#4]
Cant build

```
erik@bionic-dev-1:~/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller$ make build
rm -rf .tox/
rm -rf ./build/builds
rm -rf ./build/deps
rm -rf charm-store-push-result.txt
tox -e build
build create: /home/erik/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller/.tox/build
build installed: pkg-resources==0.0.0
build runtests: PYTHONHASHSEED='0'
build runtests: commands[0] | sh -c snap list charm 2>/dev/null || sudo snap install charm --classic
Name   Version               Rev  Tracking  Publisher  Notes
charm  2.4.5+git-1-gd62c072  298  stable    johnsca    classic
build runtests: commands[1] | charm build --log-level DEBUG -o /home/erik/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller/build src
build: Destination charm directory: /home/erik/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller/build/builds/slurm-controller
```

```
harmtools.fetchers: git clone https://git.launchpad.net/layer-leadership /home/erik/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller/build/deps/layer/tmpgg6gedyj: b"Cloning into '/home/erik/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller/build/deps/layer/tmpgg6gedyj'...\nwarning: templates not found /snap/charm/298/share/git-core/templates\n"
build: Processing layer: layer:options
build: Processing layer: layer:basic
build: Processing layer: layer:slurm (from layers/layer-slurm)
build: Processing layer: layer:munge (from layers/layer-munge)
Traceback (most recent call last):
  File "/snap/charm/298/bin/charm-build", line 9, in <module>
    load_entry_point('charm-tools==2.4.5', 'console_scripts', 'charm-build')()
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 834, in main
    build()
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 636, in __call__
    self.generate()
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 588, in generate
    self.formulate_plan(layers)
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 511, in formulate_plan
    self.plan = self.plan_layers(layers, output_files)
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 352, in plan_layers
    output_files=output_files))
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 347, in <genexpr>
    list(e for e in utils.walk(layer.directory,
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/utils.py", line 357, in walk
    yield (entry, fn(entry, **kwargs))
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/builder.py", line 323, in build_tactics
    existing_tactic,
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/tactics.py", line 54, in get
    tactic = tactic.combine(existing_tactic)
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/tactics.py", line 672, in combine
    super(MetadataYAML, self).combine(existing)
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/tactics.py", line 446, in combine
    self.data = utils.deepmerge(existing.data, self.data)
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/utils.py", line 65, in deepmerge
    dest[k].append(item)
AttributeError: 'str' object has no attribute 'append'
ERROR: InvocationError: '/snap/bin/charm build --log-level DEBUG -o /home/erik/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller/build src'
______________________________________________ summary ______________________________________________
ERROR:   build: commands failed
Makefile:20: recipe for target 'build' failed
make: *** [build] Error 1

```

My env:

```
erik@bionic-dev-1:/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller$ git remote -v
origin	https://github.com/omnivector-solutions/layer-slurm-controller (fetch)
origin	https://github.com/omnivector-solutions/layer-slurm-controller (push)
erik@bionic-dev-1:~/allcode/SLURM/juju-slurm-buildrepo/layer-slurm-controller$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

```

**Comment by dshcherb** [comment]
The error is a bit cryptic but the following part of it is a hint:

```
  File "/snap/charm/298/lib/python3.5/site-packages/charmtools/build/tactics.py", line 672, in combine
    super(MetadataYAML, self).combine(existing)
```

I commented out all layers and started adding them one by one to layer.yaml before building to do a simple debugging exercise. layer-munge turned out to be problematic:

https://github.com/omnivector-solutions/layer-munge/pull/4
